// swift-tools-version:5.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
  name: "abseil",
    platforms: [
        .macOS(.v10_10),
        .iOS(.v8),
        .tvOS(.v9)
    ],

  products: [
    .library(
      name: "abseil",
      targets: [
        "absl",
      ]
    )
  ],

  targets: [
    .target(
      name: "absl",
      path: ".",
      sources: [
        // algorithm
        "absl/algorithm/algorithm.h",
        "absl/algorithm/container.h",

        // base
        "absl/base/internal/atomic_hook.h",
        "absl/base/call_once.h",
        "absl/base/casts.h",
        "absl/base/internal/cycleclock.cc",
        "absl/base/internal/cycleclock.h",
        "absl/base/internal/low_level_scheduling.h",
        "absl/base/internal/per_thread_tls.h",
        "absl/base/internal/spinlock.cc",
        "absl/base/internal/spinlock.h",
        "absl/base/internal/sysinfo.cc",
        "absl/base/internal/sysinfo.h",
        "absl/base/internal/thread_identity.cc",
        "absl/base/internal/thread_identity.h",
        "absl/base/internal/tsan_mutex_interface.h",
        "absl/base/internal/unscaledcycleclock.cc",
        "absl/base/internal/unscaledcycleclock.h",
        "absl/base/internal/hide_ptr.h",
        "absl/base/internal/identity.h",
        "absl/base/internal/inline_variable.h",
        "absl/base/internal/invoke.h",
        "absl/base/internal/scheduling_mode.h",
        "absl/base/internal/bits.h",
        "absl/base/config.h",
        "absl/base/options.h",
        "absl/base/policy_checks.h",
        "absl/base/attributes.h",
        "absl/base/const_init.h",
        "absl/base/internal/thread_annotations.h",
        "absl/base/macros.h",
        "absl/base/optimization.h",
        "absl/base/port.h",
        "absl/base/thread_annotations.h",
        "absl/base/dynamic_annotations.cc",
        "absl/base/dynamic_annotations.h",
        "absl/base/internal/endian.h",
        "absl/base/internal/unaligned_access.h",
        "absl/base/internal/errno_saver.h",
        "absl/base/internal/exponential_biased.cc",
        "absl/base/internal/exponential_biased.h",
        "absl/base/log_severity.cc",
        "absl/base/log_severity.h",
        "absl/base/internal/direct_mmap.h",
        "absl/base/internal/low_level_alloc.cc",
        "absl/base/internal/low_level_alloc.h",
        "absl/base/internal/periodic_sampler.cc",
        "absl/base/internal/periodic_sampler.h",
        "absl/base/internal/pretty_function.h",
        "absl/base/internal/raw_logging.cc",
        "absl/base/internal/raw_logging.h",
        "absl/base/internal/spinlock_akaros.inc",
        "absl/base/internal/spinlock_linux.inc",
        "absl/base/internal/spinlock_posix.inc",
        "absl/base/internal/spinlock_wait.cc",
        "absl/base/internal/spinlock_wait.h",
        "absl/base/internal/spinlock_win32.inc",
        "absl/base/internal/throw_delegate.cc",
        "absl/base/internal/throw_delegate.h",
        "absl/meta/type_traits.h",  // meta subspec merged here to avoid circular dep.

        // container
        "absl/container/btree_map.h",
        "absl/container/btree_set.h",
        "absl/container/internal/btree.h",
        "absl/container/internal/btree_container.h",
        "absl/container/internal/common.h",
        "absl/container/internal/compressed_tuple.h",
        "absl/container/internal/container_memory.h",
        "absl/container/fixed_array.h",
        "absl/container/flat_hash_map.h",
        "absl/container/flat_hash_set.h",
        "absl/container/internal/hash_function_defaults.h",
        "absl/container/internal/hash_policy_traits.h",
        "absl/container/internal/hashtable_debug.h",
        "absl/container/internal/hashtable_debug_hooks.h",
        "absl/container/internal/hashtablez_sampler.cc",
        "absl/container/internal/hashtablez_sampler.h",
        "absl/container/internal/hashtablez_sampler_force_weak_definition.cc",
        "absl/container/internal/have_sse.h",
        "absl/container/inlined_vector.h",
        "absl/container/internal/inlined_vector.h",
        "absl/container/internal/layout.h",
        "absl/container/node_hash_map.h",
        "absl/container/internal/node_hash_policy.h",
        "absl/container/node_hash_set.h",
        "absl/container/internal/raw_hash_map.h",
        "absl/container/internal/raw_hash_set.cc",
        "absl/container/internal/raw_hash_set.h",



        // memory
        "absl/memory/memory.h",

        // numeric

        "absl/numeric/int128.cc",
        "absl/numeric/int128.h",
        "absl/numeric/int128_have_intrinsic.inc",
        "absl/numeric/int128_no_intrinsic.inc",

        // strings
        // Skipping strings/cord to avoid circular dep on container.

        "absl/strings/internal/char_map.h",
        "absl/strings/internal/escaping.cc",
        "absl/strings/internal/escaping.h",
        "absl/strings/internal/ostringstream.cc",
        "absl/strings/internal/ostringstream.h",
        "absl/strings/internal/resize_uninitialized.h",
        "absl/strings/internal/utf8.cc",
        "absl/strings/internal/utf8.h",
        "absl/strings/str_format.h",
        "absl/strings/internal/str_format/arg.cc",
        "absl/strings/internal/str_format/arg.h",
        "absl/strings/internal/str_format/bind.cc",
        "absl/strings/internal/str_format/bind.h",
        "absl/strings/internal/str_format/checker.h",
        "absl/strings/internal/str_format/extension.cc",
        "absl/strings/internal/str_format/extension.h",
        "absl/strings/internal/str_format/float_conversion.cc",
        "absl/strings/internal/str_format/float_conversion.h",
        "absl/strings/internal/str_format/output.cc",
        "absl/strings/internal/str_format/output.h",
        "absl/strings/internal/str_format/parser.cc",
        "absl/strings/internal/str_format/parser.h",
        "absl/strings/ascii.cc",
        "absl/strings/ascii.h",
        "absl/strings/charconv.cc",
        "absl/strings/charconv.h",
        "absl/strings/escaping.cc",
        "absl/strings/escaping.h",
        "absl/strings/internal/charconv_bigint.cc",
        "absl/strings/internal/charconv_bigint.h",
        "absl/strings/internal/charconv_parse.cc",
        "absl/strings/internal/charconv_parse.h",
        "absl/strings/internal/memutil.cc",
        "absl/strings/internal/memutil.h",
        "absl/strings/internal/stl_type_traits.h",
        "absl/strings/internal/str_join_internal.h",
        "absl/strings/internal/str_split_internal.h",
        "absl/strings/match.cc",
        "absl/strings/match.h",
        "absl/strings/numbers.cc",
        "absl/strings/numbers.h",
        "absl/strings/str_cat.cc",
        "absl/strings/str_cat.h",
        "absl/strings/str_join.h",
        "absl/strings/str_replace.cc",
        "absl/strings/str_replace.h",
        "absl/strings/str_split.cc",
        "absl/strings/str_split.h",
        "absl/strings/string_view.cc",
        "absl/strings/string_view.h",
        "absl/strings/strip.h",
        "absl/strings/substitute.cc",
        "absl/strings/substitute.h",

        // time
        "absl/time/internal/cctz/include/cctz/civil_time.h",
        "absl/time/internal/cctz/include/cctz/civil_time_detail.h",
        "absl/time/internal/cctz/src/civil_time_detail.cc",
        "absl/time/internal/cctz/include/cctz/time_zone.h",
        "absl/time/internal/cctz/include/cctz/zone_info_source.h",
        "absl/time/internal/cctz/src/time_zone_fixed.cc",
        "absl/time/internal/cctz/src/time_zone_fixed.h",
        "absl/time/internal/cctz/src/time_zone_format.cc",
        "absl/time/internal/cctz/src/time_zone_if.cc",
        "absl/time/internal/cctz/src/time_zone_if.h",
        "absl/time/internal/cctz/src/time_zone_impl.cc",
        "absl/time/internal/cctz/src/time_zone_impl.h",
        "absl/time/internal/cctz/src/time_zone_info.cc",
        "absl/time/internal/cctz/src/time_zone_info.h",
        "absl/time/internal/cctz/src/time_zone_libc.cc",
        "absl/time/internal/cctz/src/time_zone_libc.h",
        "absl/time/internal/cctz/src/time_zone_lookup.cc",
        "absl/time/internal/cctz/src/time_zone_posix.cc",
        "absl/time/internal/cctz/src/time_zone_posix.h",
        "absl/time/internal/cctz/src/tzfile.h",
        "absl/time/internal/cctz/src/zone_info_source.cc",
        "absl/time/civil_time.cc",
        "absl/time/civil_time.h",
        "absl/time/clock.cc",
        "absl/time/clock.h",
        "absl/time/duration.cc",
        "absl/time/format.cc",
        "absl/time/internal/get_current_time_chrono.inc",
        "absl/time/internal/get_current_time_posix.inc",
        "absl/time/time.cc",
        "absl/time/time.h",

        // types
        "absl/types/any.h",
        "absl/types/bad_any_cast.h",
        "absl/types/bad_any_cast.cc",
        "absl/types/bad_optional_access.cc",
        "absl/types/bad_optional_access.h",
        "absl/types/bad_variant_access.cc",
        "absl/types/bad_variant_access.h",
        "absl/types/compare.h",
        "absl/types/internal/optional.h",
        "absl/types/optional.h",
        "absl/types/internal/span.h",
        "absl/types/span.h",
        "absl/types/internal/variant.h",
        "absl/types/variant.h",

        // utility
        "absl/utility/utility.h"
      ],
      publicHeadersPath: ".",
      cSettings: [
        .headerSearchPath("./"),
      ]
    ),
  ],

  cxxLanguageStandard: CXXLanguageStandard.gnucxx14
)

